### ISSUE TITLE
Integrating Echo Framework with Vaadin for better styling options

### ISSUE THREAD

**Issue by akhtarm** [echo3/echo3#95]
I would like to integrate the Vaadin framework into a legacy project built on Echo3 Framework. I am doing this so that I can use CSS to improve the design. I find Vaadin quite good for this task. Is there any support available for this?

**Comment by bentolor** [comment]
Vaadin uses a complete own set of CSS classes which will only work with HTML code rendered by Vaadin. In #71 we discussed various options to make Echo style-able by plain CSS. 

As of today you already can include CSS Sheets in an Echo3 application. The main thing missing is, how to identify the elements via CSS selectors. If I remember right, the latest version already provides CSS classes for components (so you are able to style i.e. TextField). The only thing left to fully style a Echo3 application using CSS is the possiblity to assign custom class. @ceari  developed a patch fullfilling this: a7a47d106f6ad68350e4027fa784ec2398b62d31

So if your main concern & effort is to be able to style a echo3 application using a CSS stylesheet I'd rather use the patch mentioned above and incrementally replace the Echo Style Sheets with standard CSS.

**Comment by bentolor** [comment]
I'll close this issue for now, because the feature request itself does not make much sense. Please feel free to reopen/comment on further issues.

**Comment by akhtarm** [comment]
Hi,
Basically I'm working on an existing application and it uses Echo3 and it doesn't contain any css and js files. I saw the patch provided by you but I'm not sure how to use it. Is there any documentation? or should I upgrade to 3.0.2. also the application is quite messy and I'm not sure if upgrading echo will be easy. The file structure in the project is totally different from your github version.

Thanks & Regards

**Comment by bentolor** [comment]
You are able to register & populate CSS stylesheets in an Echo application i.e. as you can see in https://github.com/exxcellent/echolot/blob/master/echolot-webcontainer/src/main/java/de/exxcellent/echolot/webcontainer/sync/component/FlexiGridPeer.java#L73] ff.

The mentioned patch will become relevant if you actually start using CSS styles and you have difficulties to address elements due to missing identifiers like CSS classes in the generated HTML page/DOM.
