### ISSUE TITLE
Old releases are not avaiable via download

### ISSUE THREAD

**Issue by andreasbaumann** [echo3/echo3#96]
The page:

http://echo.nextapp.com/site/echo3/download/archive.html

references old builds like:

http://download.nextapp.com/downloads/echo3/3.0.beta8/NextApp_Echo.3.0.b8.tgz

It seems download.nextapp.com has disappeared.

**Comment by bentolor** [comment]
This host is not under our control, so I'm unable to recover the files themself. The Github repo you are seeing here is a community-driven effort.

So I'm unable to deliver you with the binaries. Nonetheless you should be able to retrieve the version and rebuild them by yourself easily. The old releases are not really tagged, but you can find out the version by looking at the history of https://github.com/echo3/echo3/commits/master/ant.properties

Does this solve your original issue?

**Comment by andreasbaumann** [comment]
Thanks for your fast feedback. No problem, we habe a copy of the binary release stowed away and
as you say we can rebuild the version in the worst case. Solved from my point of view, thanks.

**Comment by bentolor** [comment]
If you have them, maybe we could archive them here in a Github repository and adjust the links on the website.

Would you be interested in that? If yes I can create a repository "archive" here in the echo3 organisation for that purpose.
