### ISSUE TITLE
Echo Wikipedia page marked for deletion

### ISSUE THREAD

**Issue by tkuhn** [echo3/echo3#97]
Not exactly an issue of this repo, but the Wikipedia article on the Echo framework is marked for deletion: https://en.wikipedia.org/wiki/Echo_(framework)

Maybe that's OK, but if somebody here feels strongly about it now would be the time to prevent it.

I just made a very quick search myself to find an independent source describing Echo but couldn't find anything.

**Comment by bentolor** [comment]
Thanks @tkuhn for the notice!

It seems that a Wikipedia user has removed some of the dead links and the deletion notice. I'm not familiar enough with the Wikipedia convention if this means the danger has been averted.

**Comment by bentolor** [comment]
Obviously its still alive'n kicking.
